export default [
  { id: 1, skill: "HTML / HTML5" },
  { id: 2, skill: "CSS / CSS3" },
  { id: 3, skill: "JavaScript / ES6" },
  { id: 4, skill: "Ruby / Ruby on Rails" },
  { id: 5, skill: "React.js" },
  { id: 6, skill: "Redux.js" },
  { id: 7, skill: "Gatsby.js" },
  { id: 8, skill: "Sass" },
  { id: 9, skill: "Bootstrap" },
  { id: 10, skill: "Bulma" },
  { id: 11, skill: "npm" },
  { id: 12, skill: "Webpack" },
  { id: 13, skill: "Babel" },
  { id: 14, skill: "Git" },
  { id: 15, skill: "Github" },
  { id: 16, skill: "SQL" },
];
