export default [
  { id: 1, skill: "HTML / HTML5" },
  { id: 2, skill: "CSS / CSS3" },
  { id: 3, skill: "JavaScript / ES6" },
  { id: 4, skill: "Ruby" },
  { id: 5, skill: "Ruby on Rails" },
  { id: 6, skill: "React.js" },
  { id: 7, skill: "Redux.js" },
  { id: 8, skill: "Gatsby.js" },
  { id: 9, skill: "Sass" },
  { id: 10, skill: "Bootstrap" },
  { id: 11, skill: "npm" },
  { id: 12, skill: "Webpack" },
  { id: 13, skill: "Babel" },
  { id: 14, skill: "Git" },
  { id: 15, skill: "Github" },
  { id: 16, skill: "Express" },
  { id: 17, skill: "Node" },
  { id: 18, skill: "SQL" },
  { id: 19, skill: "Material UI" },
  { id: 20, skill: "Firebase" },
  { id: 21, skill: "NoSQL" },
];
